EG-1197 Synchronize choice stanza with viewer for date updates
hmrc/external-guidance pull request #108
Opened 2021-01-25 17:07 UTC by woollett-r

2021-01-25 18:20 UTC, cmrhmrc commented on app/core/models/ocelot/stanzas/ChoiceStanza.scala
> +  def moreThanOrEquals(date: LocalDate, other: LocalDate): Boolean = date.compareTo(other) >= 0
See comment on viewer PR

2021-01-25 18:20 UTC, cmrhmrc commented on test/core/models/ocelot/stanzas/ChoiceStanzaSpec.scala
> +    "deserialize from json" in {
As viewer PR

2021-01-25 18:23 UTC, cmrhmrc requested changes
ChoiceTest fns as comment

2021-01-26 14:35 UTC, woollett-r commented on test/core/models/ocelot/stanzas/ChoiceStanzaSpec.scala
> +    "deserialize from json" in {
Done

2021-01-26 18:02 UTC, merged